-- ============================================================
-- 05_grant_permissions.sql
-- Purpose: Grant permissions to LOADER and TRANSFORMER roles
-- Run as: ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- warehouse access for both roles
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORMER;

-- LOADER permissions — RAW schema only (dev + prod)
GRANT USAGE ON DATABASE STOCK_DB_DEV TO ROLE LOADER;
GRANT USAGE ON DATABASE STOCK_DB_PROD TO ROLE LOADER;

GRANT USAGE ON SCHEMA STOCK_DB_DEV.RAW TO ROLE LOADER;
GRANT USAGE ON SCHEMA STOCK_DB_PROD.RAW TO ROLE LOADER;

GRANT CREATE TABLE ON SCHEMA STOCK_DB_DEV.RAW TO ROLE LOADER;
GRANT CREATE TABLE ON SCHEMA STOCK_DB_PROD.RAW TO ROLE LOADER;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_DEV.RAW TO ROLE LOADER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_PROD.RAW TO ROLE LOADER;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_DEV.RAW TO ROLE LOADER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_PROD.RAW TO ROLE LOADER;

-- TRANSFORMER permissions — read RAW, write STAGING + MARTS (dev + prod)
GRANT USAGE ON DATABASE STOCK_DB_DEV TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE STOCK_DB_PROD TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA STOCK_DB_DEV.RAW     TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA STOCK_DB_DEV.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA STOCK_DB_DEV.MARTS   TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA STOCK_DB_PROD.RAW     TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA STOCK_DB_PROD.STAGING TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA STOCK_DB_PROD.MARTS   TO ROLE TRANSFORMER;

GRANT SELECT ON ALL TABLES IN SCHEMA STOCK_DB_DEV.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA STOCK_DB_PROD.RAW TO ROLE TRANSFORMER;

GRANT CREATE TABLE ON SCHEMA STOCK_DB_DEV.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA STOCK_DB_DEV.MARTS   TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA STOCK_DB_PROD.STAGING TO ROLE TRANSFORMER;
GRANT CREATE TABLE ON SCHEMA STOCK_DB_PROD.MARTS   TO ROLE TRANSFORMER;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_DEV.STAGING TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_DEV.MARTS   TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_PROD.STAGING TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA STOCK_DB_PROD.MARTS   TO ROLE TRANSFORMER;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_DEV.STAGING TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_DEV.MARTS   TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_PROD.STAGING TO ROLE TRANSFORMER;
GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA STOCK_DB_PROD.MARTS   TO ROLE TRANSFORMER;

-- Future tables — so TRANSFORMER can read new RAW tables automatically
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCK_DB_DEV.RAW  TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCK_DB_PROD.RAW TO ROLE TRANSFORMER;