# ============================================================
# dbt_project.yml
# Project: finance_pipeline
# ============================================================
name: 'finance_pipeline'
version: '1.0.0'
profile: 'finance_pipeline'

# File paths
model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  finance_pipeline:
    staging:
      +schema:       STAGING
      +materialized: view
    marts:
      +schema:       MARTS
      +materialized: table